# Generated by Django 3.2.9 on 2023-01-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('genero', models.CharField(default='desconocido', max_length=200, verbose_name='Genero')),
                ('imagen', models.CharField(help_text='Inserte el file_id de la foto, lo puede obtener solo enviando la foto al chat del bot', max_length=100, verbose_name='Foto')),
                ('capitulos', models.CharField(help_text="Inserte la cantidad de capitulos si no tiene capitulos inserte 'En Transmision'", max_length=50, verbose_name='Capitulos')),
                ('compania', models.CharField(max_length=100, verbose_name='Compania que lo hizo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.category')),
            ],
        ),
    ]
